/**
 * QR payload contract (spec §5 printable QR, Phase 6).
 *
 * A Gubbins item QR encodes a **deep-link URL** of the form
 * `…/Gubbins/#/inventory?item=<uuid>` so that any phone camera scanning it opens
 * the app straight to that item, while the in-app scanner extracts the id back out.
 * For robustness the parser also accepts a bare UUID and a namespaced
 * `gubbins:item:<uuid>` token, so a code generated by an older/other tool still
 * resolves. All logic here is pure and unit-tested; the camera/Barcode-Detection
 * side (browser-only) merely feeds raw decoded strings into {@link parseScannedItemId}.
 */
import { ITEM_QR_PARAM } from '@/db/repositories/constants';

/** A canonical UUID (any version), case-insensitive. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const NAMESPACED_PREFIX = 'gubbins:item:';

/** True when `value` is a syntactically valid UUID. */
export function isUuid(value: string): boolean {
  return UUID_RE.test(value.trim());
}

/**
 * Build the printable deep-link payload for an item.
 *
 * @param itemId  The item's UUID.
 * @param baseUrl The app base ending in the `/Gubbins/` path — typically
 *   `new URL(import.meta.env.BASE_URL, location.origin)` at runtime. Falsy/`'#'`
 *   yields a hash-only link, still parseable by the in-app scanner.
 */
export function buildItemQrUrl(itemId: string, baseUrl: string): string {
  const hash = `#/inventory?${ITEM_QR_PARAM}=${encodeURIComponent(itemId)}`;
  if (!baseUrl || baseUrl === '#') return hash;
  // Strip any existing hash from the base, then append ours.
  const base = baseUrl.split('#')[0];
  return `${base}${hash}`;
}

/**
 * Extract a Gubbins item id from a raw scanned/typed string, or `null` if it does
 * not look like a Gubbins item code. Accepts (in order): a full deep-link URL with
 * `?item=<uuid>` in its hash or query, the `gubbins:item:<uuid>` token, or a bare UUID.
 */
export function parseScannedItemId(raw: string): string | null {
  const text = raw.trim();
  if (text.length === 0) return null;

  // 1) bare UUID
  if (isUuid(text)) return text.toLowerCase();

  // 2) namespaced token
  if (text.toLowerCase().startsWith(NAMESPACED_PREFIX)) {
    const id = text.slice(NAMESPACED_PREFIX.length).trim();
    return isUuid(id) ? id.toLowerCase() : null;
  }

  // 3) URL — look for the item param in the hash's query string first, then the
  //    top-level query string (covers both hash- and path-based deep links).
  try {
    const url = new URL(text);
    const fromHash = paramFromQueryString(url.hash.replace(/^#/, ''));
    if (fromHash) return fromHash;
    const fromSearch = url.searchParams.get(ITEM_QR_PARAM);
    if (fromSearch && isUuid(fromSearch)) return fromSearch.toLowerCase();
  } catch {
    // not a URL — fall through
  }
  return null;
}

/** Pull `item=<uuid>` out of a `path?item=…&…` style fragment, if present & valid. */
function paramFromQueryString(fragment: string): string | null {
  const qIndex = fragment.indexOf('?');
  if (qIndex === -1) return null;
  const params = new URLSearchParams(fragment.slice(qIndex + 1));
  const id = params.get(ITEM_QR_PARAM);
  return id && isUuid(id) ? id.toLowerCase() : null;
}
