/**
 * QR payload contract (spec §5 printable QR, Phase 6; location codes added Phase 73).
 *
 * A Gubbins item QR encodes a **deep-link URL** of the form
 * `…/Gubbins/#/inventory?item=<uuid>` so that any phone camera scanning it opens
 * the app straight to that item, while the in-app scanner extracts the id back out.
 * A **location** label encodes `…/Gubbins/#/inventory?location=<uuid>` and selects
 * that location (Phase 73). For robustness the parser also accepts a bare UUID and
 * the namespaced `gubbins:item:<uuid>` / `gubbins:location:<uuid>` tokens, so a code
 * generated by an older/other tool still resolves. All logic here is pure and
 * unit-tested; the camera/Barcode-Detection side (browser-only) merely feeds raw
 * decoded strings into {@link parseScannedCode}.
 */
import { ITEM_QR_PARAM, LOCATION_QR_PARAM } from '@/db/repositories/constants';

/** A canonical UUID (any version), case-insensitive. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const NAMESPACED_ITEM_PREFIX = 'gubbins:item:';
const NAMESPACED_LOCATION_PREFIX = 'gubbins:location:';

/** A decoded Gubbins code: an item deep-link or a location deep-link. */
export type ScannedCode =
  | { readonly kind: 'item'; readonly id: string }
  | { readonly kind: 'location'; readonly id: string };

/** True when `value` is a syntactically valid UUID. */
export function isUuid(value: string): boolean {
  return UUID_RE.test(value.trim());
}

/**
 * Build the printable deep-link payload for an item.
 *
 * @param itemId  The item's UUID.
 * @param baseUrl The app base ending in the `/Gubbins/` path — typically
 *   `new URL(import.meta.env.BASE_URL, location.origin)` at runtime. Falsy/`'#'`
 *   yields a hash-only link, still parseable by the in-app scanner.
 */
export function buildItemQrUrl(itemId: string, baseUrl: string): string {
  return buildDeepLink(ITEM_QR_PARAM, itemId, baseUrl);
}

/**
 * Build the printable deep-link payload for a **location** (Phase 73). Mirrors
 * {@link buildItemQrUrl}; encodes `…/#/inventory?location=<uuid>`.
 */
export function buildLocationQrUrl(locationId: string, baseUrl: string): string {
  return buildDeepLink(LOCATION_QR_PARAM, locationId, baseUrl);
}

function buildDeepLink(param: string, id: string, baseUrl: string): string {
  const hash = `#/inventory?${param}=${encodeURIComponent(id)}`;
  if (!baseUrl || baseUrl === '#') return hash;
  // Strip any existing hash from the base, then append ours.
  const base = baseUrl.split('#')[0];
  return `${base}${hash}`;
}

/**
 * Decode a raw scanned/typed string into a tagged {@link ScannedCode}, or `null` if
 * it is not a recognisable Gubbins code. Accepts, in order: a **bare UUID** (always an
 * item, preserving the original Phase-6 contract); the `gubbins:location:<uuid>` /
 * `gubbins:item:<uuid>` tokens; or a deep-link URL carrying `?location=<uuid>` or
 * `?item=<uuid>` in its hash query (checked first) or top-level query. The two params
 * are disjoint, so an item code never resolves as a location or vice-versa.
 */
export function parseScannedCode(raw: string): ScannedCode | null {
  const text = raw.trim();
  if (text.length === 0) return null;

  // 1) bare UUID → item (the pre-Phase-73 contract; item codes are bare UUIDs).
  if (isUuid(text)) return { kind: 'item', id: text.toLowerCase() };

  // 2) namespaced tokens.
  const lower = text.toLowerCase();
  if (lower.startsWith(NAMESPACED_LOCATION_PREFIX)) {
    const id = text.slice(NAMESPACED_LOCATION_PREFIX.length).trim();
    return isUuid(id) ? { kind: 'location', id: id.toLowerCase() } : null;
  }
  if (lower.startsWith(NAMESPACED_ITEM_PREFIX)) {
    const id = text.slice(NAMESPACED_ITEM_PREFIX.length).trim();
    return isUuid(id) ? { kind: 'item', id: id.toLowerCase() } : null;
  }

  // 3) URL — look in the hash's query string first, then the top-level query string
  //    (covers both hash- and path-based deep links). Location is checked before item.
  try {
    const url = new URL(text);
    const fragment = url.hash.replace(/^#/, '');
    const loc =
      paramFromQueryString(fragment, LOCATION_QR_PARAM) ?? validId(url.searchParams.get(LOCATION_QR_PARAM));
    if (loc) return { kind: 'location', id: loc };
    const item =
      paramFromQueryString(fragment, ITEM_QR_PARAM) ?? validId(url.searchParams.get(ITEM_QR_PARAM));
    if (item) return { kind: 'item', id: item };
  } catch {
    // not a URL — fall through
  }
  return null;
}

/**
 * Extract a Gubbins **item** id from a raw scanned/typed string, or `null` if it is
 * not an item code (a location code returns `null` here). A thin wrapper over
 * {@link parseScannedCode} kept for the item-only call sites.
 */
export function parseScannedItemId(raw: string): string | null {
  const code = parseScannedCode(raw);
  return code?.kind === 'item' ? code.id : null;
}

/** A valid lower-cased UUID, or `null`. */
function validId(value: string | null): string | null {
  return value && isUuid(value) ? value.toLowerCase() : null;
}

/** Pull `<param>=<uuid>` out of a `path?param=…&…` style fragment, if present & valid. */
function paramFromQueryString(fragment: string, param: string): string | null {
  const qIndex = fragment.indexOf('?');
  if (qIndex === -1) return null;
  const params = new URLSearchParams(fragment.slice(qIndex + 1));
  return validId(params.get(param));
}
