/**
 * QR payload contract (spec §5 printable QR, Phase 6; location codes added Phase 73).
 *
 * A Gubbins item QR encodes a **deep-link URL** of the form
 * `…/Gubbins/#/inventory?item=<uuid>` so that any phone camera scanning it opens
 * the app straight to that item, while the in-app scanner extracts the id back out.
 * A **location** label encodes `…/Gubbins/#/inventory?location=<uuid>` and selects
 * that location (Phase 73). For robustness the parser also accepts a bare UUID and
 * the namespaced `gubbins:item:<uuid>` / `gubbins:location:<uuid>` tokens, so a code
 * generated by an older/other tool still resolves. All logic here is pure and
 * unit-tested; the camera/Barcode-Detection side (browser-only) merely feeds raw
 * decoded strings into {@link parseScannedCode}.
 *
 * A scan that is **not** a Gubbins code but is a valid retail **GTIN** (EAN/UPC
 * barcode) is recognised as a third `gtin` kind (recommendation point 1), so the
 * scanner can offer to record it against an item or look the product up, rather than
 * dead-ending on "not a Gubbins code". GTIN validation lives in the pure {@link parseGtin}.
 */
import { ITEM_QR_PARAM, LOCATION_QR_PARAM } from '@/db/repositories/constants';
import { parseGtin } from './gtin';

/** A canonical UUID (any version), case-insensitive. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const NAMESPACED_ITEM_PREFIX = 'gubbins:item:';
const NAMESPACED_LOCATION_PREFIX = 'gubbins:location:';

/**
 * A decoded scan: a Gubbins item/location deep-link, or a retail `gtin` barcode that
 * isn't a Gubbins code at all (the "unknown product" fallback, recommendation point 1).
 */
export type ScannedCode =
  | { readonly kind: 'item'; readonly id: string }
  | { readonly kind: 'location'; readonly id: string }
  | { readonly kind: 'gtin'; readonly gtin: string };

/**
 * True when `value` is a syntactically valid UUID.
 *
 * @internal Exported for unit tests only.
 */
export function isUuid(value: string): boolean {
  return UUID_RE.test(value.trim());
}

/**
 * A printed **short code** — the first group of an id's UUID, as `shortId` renders it onto a
 * label (issue #338). Eight hex characters, in either case.
 */
const SHORT_CODE_RE = /^[0-9a-f]{8}$/i;

/**
 * True when `value` has the shape of a label's printed short code — the fallback identifier
 * `shortId` (`labels/label-template.ts`) puts on every label and uses as the Code 128 fallback
 * value when the preferred one is too long to print (issue #331).
 *
 * Deliberately a *shape* test rather than a parse: a short code names no record on its own, so
 * it can only be resolved by asking the database (`ItemRepository.findByShortCode`, or a scan
 * of the loaded locations). It is therefore **not** a {@link ScannedCode} kind — a caller
 * checks this, then looks the code up, rather than being handed an id it cannot use. A unit
 * test pins it against `shortId`'s own output so the printed form and the recognised form
 * cannot drift apart.
 *
 * Note the overlap with an 8-digit GTIN-8: callers resolve a valid GTIN first, so a genuine
 * retail barcode is never mistaken for a short code.
 */
export function isShortItemCode(value: string): boolean {
  return SHORT_CODE_RE.test(value.trim());
}

/**
 * Build the printable deep-link payload for an item.
 *
 * @param itemId  The item's UUID.
 * @param baseUrl The app base ending in the `/Gubbins/` path — typically
 *   `new URL(import.meta.env.BASE_URL, location.origin)` at runtime. Falsy/`'#'`
 *   yields a hash-only link, still parseable by the in-app scanner.
 */
export function buildItemQrUrl(itemId: string, baseUrl: string): string {
  return buildDeepLink(ITEM_QR_PARAM, itemId, baseUrl);
}

/**
 * Build the printable deep-link payload for a **location** (Phase 73). Mirrors
 * {@link buildItemQrUrl}; encodes `…/#/inventory?location=<uuid>`.
 */
export function buildLocationQrUrl(locationId: string, baseUrl: string): string {
  return buildDeepLink(LOCATION_QR_PARAM, locationId, baseUrl);
}

function buildDeepLink(param: string, id: string, baseUrl: string): string {
  const hash = `#/inventory?${param}=${encodeURIComponent(id)}`;
  if (!baseUrl || baseUrl === '#') return hash;
  // Strip any existing hash from the base, then append ours.
  const base = baseUrl.split('#')[0];
  return `${base}${hash}`;
}

/**
 * Resolve the base URL that printable item/location codes should point at.
 *
 * A code encodes an absolute deep-link (`<base>#/inventory?item=<id>`), and by default
 * `<base>` is derived from the running page: the deployment `origin` (e.g.
 * `http://localhost:5173`) plus the Vite `basePath` (`import.meta.env.BASE_URL`, e.g.
 * `/Gubbins/`). That is fine when you always open the app the same way, but a label
 * printed from a `localhost` dev server — or from one device's IP — is useless on a
 * phone. The optional `override` (Settings → "Link host") replaces the derived base
 * entirely, so codes can point at a stable name every device can reach, e.g.
 * `https://gubbins.local/`.
 *
 * `override` is forgiving: a full URL (`https://gubbins.local/Gubbins/`) is used as-is,
 * and a bare host (`gubbins.local:8080`) is assumed to be `https://` — see
 * {@link isInsecureLabelBaseUrl} for why plain `http://` is the wrong guess. A blank or
 * unparseable override falls back to the derived default. When there is no `origin`
 * (no DOM — tests/SSR) and no usable override, returns `'#'` so callers still emit a
 * hash-only link the in-app scanner can parse. Never throws.
 */
export function resolveLabelBaseUrl(override: string, origin: string | null, basePath: string): string {
  const custom = parseOverrideBase(override);
  if (custom) return custom;
  if (!origin) return '#';
  try {
    return new URL(basePath, origin).href;
  } catch {
    return '#';
  }
}

/**
 * Hostnames a browser still treats as a **secure context** over plain `http://`: the loopback
 * set, plus the `*.localhost` names browsers resolve to it. Everything else must be `https://`.
 */
function isLoopbackHostname(hostname: string): boolean {
  const host = hostname.toLowerCase().replace(/^\[|\]$/g, '');
  if (host === 'localhost' || host.endsWith('.localhost')) return true;
  if (host === '::1' || host === '0:0:0:0:0:0:0:1') return true;
  // The whole 127.0.0.0/8 block, but only as a literal address — `127.example.com` is an
  // ordinary registrable name a browser does not trust. `new URL` has already canonicalised
  // shorthand forms (`127.1`) to four octets by the time a hostname reaches here.
  return /^127(?:\.\d{1,3}){3}$/.test(host);
}

/**
 * True when a resolved label base **cannot open Gubbins at all**: a plain `http://` address
 * that is not loopback is never a secure context, and the boot gate treats that as fatal
 * (`support-diagnosis.ts` → `'insecure-context'`) because OPFS is unavailable there. Codes
 * printed against such a base scan to the boot-failure screen, never to the item — and a
 * label is physical, so the only fix is to reprint the sheet. Settings warns on this before
 * anything is printed.
 */
export function isInsecureLabelBaseUrl(base: string): boolean {
  try {
    const url = new URL(base);
    return url.protocol === 'http:' && !isLoopbackHostname(url.hostname);
  } catch {
    return false;
  }
}

/**
 * Pick the scheme for a **scheme-less** "Link host". `https:` for anything but loopback:
 * Gubbins needs a secure context to boot, so the old `http:` guess turned `gubbins.local`
 * into a base no scanned label could ever open. A loopback name keeps `http:`, which is
 * both what a dev server serves and still a secure context.
 */
function guessScheme(hostish: string): 'http' | 'https' {
  try {
    return isLoopbackHostname(new URL(`http://${hostish}`).hostname) ? 'http' : 'https';
  } catch {
    return 'https';
  }
}

/**
 * Parse a user-typed "Link host" into a normalised absolute base URL, or `null` when it
 * is blank or cannot be made into an `http(s)` URL. A value carrying its own scheme is
 * used verbatim; a scheme-less one is prefixed by {@link guessScheme}.
 */
function parseOverrideBase(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  // Guess a scheme only when the value carries none of its own (so a lone `http://` isn't
  // "helpfully" turned into `http://http://…`).
  const hasScheme = /^[a-z][a-z0-9+.-]*:\/\//i.test(trimmed);
  const candidate = hasScheme ? trimmed : `${guessScheme(trimmed)}://${trimmed}`;
  try {
    const url = new URL(candidate);
    if ((url.protocol === 'http:' || url.protocol === 'https:') && url.hostname) return url.href;
  } catch {
    // fall through to the derived default
  }
  return null;
}

/**
 * Decode a raw scanned/typed string into a tagged {@link ScannedCode}, or `null` if
 * it is not a recognisable Gubbins code. Accepts, in order: a **bare UUID** (always an
 * item, preserving the original Phase-6 contract); the `gubbins:location:<uuid>` /
 * `gubbins:item:<uuid>` tokens; or a deep-link URL carrying `?location=<uuid>` or
 * `?item=<uuid>` in its hash query (checked first) or top-level query. The two params
 * are disjoint, so an item code never resolves as a location or vice-versa.
 */
export function parseScannedCode(raw: string): ScannedCode | null {
  const text = raw.trim();
  if (text.length === 0) return null;

  // 1) bare UUID → item (the pre-Phase-73 contract; item codes are bare UUIDs).
  if (isUuid(text)) return { kind: 'item', id: text.toLowerCase() };

  // 2) namespaced tokens.
  const lower = text.toLowerCase();
  if (lower.startsWith(NAMESPACED_LOCATION_PREFIX)) {
    const id = text.slice(NAMESPACED_LOCATION_PREFIX.length).trim();
    return isUuid(id) ? { kind: 'location', id: id.toLowerCase() } : null;
  }
  if (lower.startsWith(NAMESPACED_ITEM_PREFIX)) {
    const id = text.slice(NAMESPACED_ITEM_PREFIX.length).trim();
    return isUuid(id) ? { kind: 'item', id: id.toLowerCase() } : null;
  }

  // 3) URL — look in the hash's query string first, then the top-level query string
  //    (covers both hash- and path-based deep links). Location is checked before item.
  try {
    const url = new URL(text);
    const fragment = url.hash.replace(/^#/, '');
    const loc =
      paramFromQueryString(fragment, LOCATION_QR_PARAM) ?? validId(url.searchParams.get(LOCATION_QR_PARAM));
    if (loc) return { kind: 'location', id: loc };
    const item =
      paramFromQueryString(fragment, ITEM_QR_PARAM) ?? validId(url.searchParams.get(ITEM_QR_PARAM));
    if (item) return { kind: 'item', id: item };
  } catch {
    // not a URL — fall through
  }

  // 4) Not a Gubbins code — is it a plain retail barcode? A valid GTIN (EAN/UPC) is the
  //    "unknown product" fallback. Checked last so a Gubbins deep-link always wins.
  const gtin = parseGtin(text);
  if (gtin) return { kind: 'gtin', gtin };

  return null;
}

/**
 * Extract a Gubbins **item** id from a raw scanned/typed string, or `null` if it is
 * not an item code (a location code or a plain GTIN barcode returns `null` here). A
 * thin wrapper over {@link parseScannedCode} kept for the item-only call sites.
 */
export function parseScannedItemId(raw: string): string | null {
  const code = parseScannedCode(raw);
  return code?.kind === 'item' ? code.id : null;
}

/** A `scheme://…` URL (http, https, whatsapp, …) — the leading scheme of a full URL. */
const URL_SCHEME_RE = /^[a-z][a-z0-9+.-]*:\/\//i;
/** URI schemes a QR code commonly carries that are structured payloads, not barcodes. */
const NON_PRODUCT_URI_SCHEME_RE = /^(mailto|tel|sms|smsto|geo|wifi|matmsg|bitcoin|upi|otpauth|market):/i;
/** Structured-QR block formats (contact / calendar / Wi-Fi) that begin with a keyword. */
const STRUCTURED_QR_BLOCK_RE = /^(BEGIN:V(CARD|EVENT)|MECARD:|WIFI:)/i;
/** A scheme-less bare domain with a path, e.g. `wa.me/message/…` or `www.example.com/x`. */
const BARE_DOMAIN_PATH_RE = /^(www\.)?[a-z0-9-]+(\.[a-z0-9-]+)+\/\S*$/i;

/**
 * True when a decoded string is a **structured QR payload** — a website link, contact card,
 * Wi-Fi/geo/tel URI, and the like — rather than a product barcode (issue #59). Retail
 * packaging increasingly prints a marketing QR beside the barcode; decoding *that* must not be
 * quietly dropped into the Barcode field. A plain alphanumeric part label (Code 128 / Code 39)
 * is deliberately **not** flagged, so genuine linear codes still capture verbatim.
 */
export function isStructuredQrPayload(raw: string): boolean {
  const text = raw.trim();
  if (text.length === 0) return false;
  if (URL_SCHEME_RE.test(text)) return true; // scheme://… (http, https, whatsapp, …)
  if (NON_PRODUCT_URI_SCHEME_RE.test(text)) return true; // mailto:, tel:, wifi:, …
  if (STRUCTURED_QR_BLOCK_RE.test(text)) return true; // vCard / vEvent / MECARD / WIFI
  if (!/\s/.test(text) && BARE_DOMAIN_PATH_RE.test(text)) return true; // wa.me/… without a scheme
  return false;
}

/**
 * Resolve a decoded scan to an **openable `http(s)` link**, or `null` when it isn't one.
 * Used by the barcode dialog to offer "open this link" for a marketing QR (issue #59) instead
 * of capturing its URL as a barcode. Only `http:` / `https:` are returned — a `javascript:`,
 * `data:`, `tel:` or other scheme is never openable — and a scheme-less bare domain
 * (`wa.me/…`) is promoted to `https://`. Never throws.
 */
export function asOpenableLink(raw: string): string | null {
  const text = raw.trim();
  if (text.length === 0) return null;
  // A full URL is taken as-is; a scheme-less bare domain (`wa.me/…`) is promoted to https; a
  // whitespace-bearing or non-domain string is not a link at all.
  let candidate: string | null;
  if (URL_SCHEME_RE.test(text)) candidate = text;
  else if (/\s/.test(text) || !BARE_DOMAIN_PATH_RE.test(text)) candidate = null;
  else candidate = `https://${text}`;
  if (candidate === null) return null;
  try {
    const url = new URL(candidate);
    return url.protocol === 'http:' || url.protocol === 'https:' ? url.href : null;
  } catch {
    return null;
  }
}

/** A valid lower-cased UUID, or `null`. */
function validId(value: string | null): string | null {
  return value && isUuid(value) ? value.toLowerCase() : null;
}

/** Pull `<param>=<uuid>` out of a `path?param=…&…` style fragment, if present & valid. */
function paramFromQueryString(fragment: string, param: string): string | null {
  const qIndex = fragment.indexOf('?');
  if (qIndex === -1) return null;
  const params = new URLSearchParams(fragment.slice(qIndex + 1));
  return validId(params.get(param));
}
