/**
 * Curated Unicode-emoji catalogue for the app-wide {@link EmojiPicker} (issue #83).
 *
 * A deliberately hand-picked, inventory-leaning subset of the standard Unicode emoji
 * groups rather than the full ~1,900-code set: every emoji here reads clearly at a small
 * size, renders on the common platform fonts, and is the kind of glyph a user actually
 * reaches for to mark a *category* (a battery, a book, a screwdriver…). Keeping it curated
 * also keeps the picker's grid legible and its search results relevant.
 *
 * Each entry carries its display `name` (the accessible label + primary search text) and
 * optional extra `keywords` (synonyms that aren't in the name), so a search for "car"
 * finds 🚗 and "screw" finds 🔩. The data is pure and lucide-free; the picker imports it
 * lazily so the catalogue never lands in the main bundle.
 */

/** One emoji: its character, human name, and optional extra search synonyms. */
export interface EmojiEntry {
  /** The emoji character itself (the stored/selected value). */
  readonly char: string;
  /** Human-readable name — the accessible label and primary search text. */
  readonly name: string;
  /** Extra search synonyms not already present in {@link name} (space-separated). */
  readonly keywords?: string;
}

/** A browse group in the picker's left-hand rail — a stable id, a label, and its emoji. */
export interface EmojiGroup {
  /** Stable slug — the rail key and a durable identifier, never shown to the user. */
  readonly id: string;
  /** User-facing group label (English source copy). */
  readonly label: string;
  /** The emoji filed under this group, in display order. */
  readonly emojis: readonly EmojiEntry[];
}

/**
 * The curated groups, in rail order. Ids are stable slugs; labels are the shipped English
 * copy. Ordering within each group is roughly most-common-first.
 */
export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    id: 'smileys',
    label: 'Smileys & emotion',
    emojis: [
      { char: '😀', name: 'Grinning face', keywords: 'smile happy' },
      { char: '😄', name: 'Grinning face with smiling eyes', keywords: 'happy joy' },
      { char: '😁', name: 'Beaming face', keywords: 'grin happy' },
      { char: '😊', name: 'Smiling face', keywords: 'blush happy' },
      { char: '🙂', name: 'Slightly smiling face', keywords: 'smile' },
      { char: '😉', name: 'Winking face', keywords: 'wink' },
      { char: '😍', name: 'Smiling face with heart-eyes', keywords: 'love' },
      { char: '😎', name: 'Smiling face with sunglasses', keywords: 'cool' },
      { char: '🤩', name: 'Star-struck', keywords: 'excited star' },
      { char: '😇', name: 'Smiling face with halo', keywords: 'angel innocent' },
      { char: '🤔', name: 'Thinking face', keywords: 'ponder' },
      { char: '🤨', name: 'Face with raised eyebrow', keywords: 'sceptic' },
      { char: '😴', name: 'Sleeping face', keywords: 'sleep tired zzz' },
      { char: '😢', name: 'Crying face', keywords: 'sad tear' },
      { char: '😡', name: 'Enraged face', keywords: 'angry mad' },
      { char: '🥳', name: 'Partying face', keywords: 'celebrate party' },
      { char: '😷', name: 'Face with medical mask', keywords: 'sick mask' },
      { char: '🤒', name: 'Face with thermometer', keywords: 'sick ill fever' },
      { char: '👻', name: 'Ghost', keywords: 'halloween spooky' },
      { char: '💀', name: 'Skull', keywords: 'death danger' },
      { char: '🤖', name: 'Robot', keywords: 'bot android' },
      { char: '👽', name: 'Alien', keywords: 'ufo space' },
      { char: '😺', name: 'Grinning cat', keywords: 'cat happy' },
      { char: '❤️', name: 'Red heart', keywords: 'love like favourite' },
      { char: '🧡', name: 'Orange heart', keywords: 'love' },
      { char: '💛', name: 'Yellow heart', keywords: 'love' },
      { char: '💚', name: 'Green heart', keywords: 'love' },
      { char: '💙', name: 'Blue heart', keywords: 'love' },
      { char: '💜', name: 'Purple heart', keywords: 'love' },
      { char: '🖤', name: 'Black heart', keywords: 'love' },
      { char: '💔', name: 'Broken heart', keywords: 'sad break' },
      { char: '💯', name: 'Hundred points', keywords: 'score perfect' },
    ],
  },
  {
    id: 'people',
    label: 'People & body',
    emojis: [
      { char: '👍', name: 'Thumbs up', keywords: 'like approve ok' },
      { char: '👎', name: 'Thumbs down', keywords: 'dislike no' },
      { char: '👌', name: 'OK hand', keywords: 'okay perfect' },
      { char: '👏', name: 'Clapping hands', keywords: 'applause' },
      { char: '🙌', name: 'Raising hands', keywords: 'celebrate hooray' },
      { char: '🙏', name: 'Folded hands', keywords: 'please thanks pray' },
      { char: '💪', name: 'Flexed biceps', keywords: 'strong muscle' },
      { char: '✋', name: 'Raised hand', keywords: 'stop high five' },
      { char: '👋', name: 'Waving hand', keywords: 'hello bye' },
      { char: '✍️', name: 'Writing hand', keywords: 'write sign note' },
      { char: '👀', name: 'Eyes', keywords: 'look see watch' },
      { char: '🧠', name: 'Brain', keywords: 'mind smart think' },
      { char: '👤', name: 'Bust in silhouette', keywords: 'person user contact' },
      { char: '👥', name: 'Busts in silhouette', keywords: 'people group users' },
      { char: '👶', name: 'Baby', keywords: 'child infant' },
      { char: '🧑', name: 'Person', keywords: 'adult human' },
      { char: '👩', name: 'Woman', keywords: 'female' },
      { char: '👨', name: 'Man', keywords: 'male' },
      { char: '👮', name: 'Police officer', keywords: 'cop security' },
      { char: '👷', name: 'Construction worker', keywords: 'builder hardhat' },
      { char: '🧑‍🍳', name: 'Cook', keywords: 'chef kitchen' },
      { char: '🧑‍🔧', name: 'Mechanic', keywords: 'repair worker' },
      { char: '🧑‍🌾', name: 'Farmer', keywords: 'agriculture' },
      { char: '🧑‍⚕️', name: 'Health worker', keywords: 'doctor nurse medical' },
      { char: '🦶', name: 'Foot', keywords: 'leg' },
      { char: '👂', name: 'Ear', keywords: 'hear listen' },
      { char: '👃', name: 'Nose', keywords: 'smell' },
      { char: '🦷', name: 'Tooth', keywords: 'dental teeth' },
    ],
  },
  {
    id: 'nature',
    label: 'Animals & nature',
    emojis: [
      { char: '🐶', name: 'Dog face', keywords: 'puppy pet' },
      { char: '🐱', name: 'Cat face', keywords: 'kitten pet' },
      { char: '🐭', name: 'Mouse face', keywords: 'rodent' },
      { char: '🐹', name: 'Hamster', keywords: 'pet rodent' },
      { char: '🐰', name: 'Rabbit face', keywords: 'bunny' },
      { char: '🦊', name: 'Fox', keywords: 'animal' },
      { char: '🐻', name: 'Bear', keywords: 'animal' },
      { char: '🐼', name: 'Panda', keywords: 'bear' },
      { char: '🐨', name: 'Koala', keywords: 'animal' },
      { char: '🦁', name: 'Lion', keywords: 'animal' },
      { char: '🐮', name: 'Cow face', keywords: 'cattle' },
      { char: '🐷', name: 'Pig face', keywords: 'pork' },
      { char: '🐔', name: 'Chicken', keywords: 'hen poultry' },
      { char: '🐧', name: 'Penguin', keywords: 'bird' },
      { char: '🐦', name: 'Bird', keywords: 'animal' },
      { char: '🦆', name: 'Duck', keywords: 'bird' },
      { char: '🦉', name: 'Owl', keywords: 'bird' },
      { char: '🐝', name: 'Honeybee', keywords: 'bee insect' },
      { char: '🐛', name: 'Bug', keywords: 'insect caterpillar' },
      { char: '🦋', name: 'Butterfly', keywords: 'insect' },
      { char: '🐌', name: 'Snail', keywords: 'slow' },
      { char: '🐢', name: 'Turtle', keywords: 'tortoise reptile' },
      { char: '🐍', name: 'Snake', keywords: 'reptile' },
      { char: '🐠', name: 'Tropical fish', keywords: 'aquarium' },
      { char: '🐟', name: 'Fish', keywords: 'sea' },
      { char: '🐙', name: 'Octopus', keywords: 'sea' },
      { char: '🦀', name: 'Crab', keywords: 'shellfish sea' },
      { char: '🌵', name: 'Cactus', keywords: 'plant desert succulent' },
      { char: '🌲', name: 'Evergreen tree', keywords: 'pine forest' },
      { char: '🌳', name: 'Tree', keywords: 'forest wood' },
      { char: '🌴', name: 'Palm tree', keywords: 'tropical' },
      { char: '🌱', name: 'Seedling', keywords: 'plant sprout grow' },
      { char: '🌿', name: 'Herb', keywords: 'plant leaf' },
      { char: '🍀', name: 'Four leaf clover', keywords: 'luck' },
      { char: '🌸', name: 'Cherry blossom', keywords: 'flower spring' },
      { char: '🌹', name: 'Rose', keywords: 'flower' },
      { char: '🌻', name: 'Sunflower', keywords: 'flower' },
      { char: '🌷', name: 'Tulip', keywords: 'flower' },
      { char: '🍄', name: 'Mushroom', keywords: 'fungus' },
      { char: '🌍', name: 'Globe showing Europe-Africa', keywords: 'earth world' },
      { char: '🌙', name: 'Crescent moon', keywords: 'night' },
      { char: '⭐', name: 'Star', keywords: 'favourite' },
      { char: '🔥', name: 'Fire', keywords: 'flame hot burn' },
      { char: '💧', name: 'Droplet', keywords: 'water drop liquid' },
      { char: '❄️', name: 'Snowflake', keywords: 'cold winter frozen' },
      { char: '⚡', name: 'High voltage', keywords: 'lightning electric power' },
      { char: '🌈', name: 'Rainbow', keywords: 'colour' },
    ],
  },
  {
    id: 'food',
    label: 'Food & drink',
    emojis: [
      { char: '🍎', name: 'Red apple', keywords: 'fruit' },
      { char: '🍏', name: 'Green apple', keywords: 'fruit' },
      { char: '🍐', name: 'Pear', keywords: 'fruit' },
      { char: '🍊', name: 'Tangerine', keywords: 'orange fruit citrus' },
      { char: '🍋', name: 'Lemon', keywords: 'fruit citrus' },
      { char: '🍌', name: 'Banana', keywords: 'fruit' },
      { char: '🍉', name: 'Watermelon', keywords: 'fruit' },
      { char: '🍇', name: 'Grapes', keywords: 'fruit wine' },
      { char: '🍓', name: 'Strawberry', keywords: 'fruit berry' },
      { char: '🫐', name: 'Blueberries', keywords: 'fruit berry' },
      { char: '🍒', name: 'Cherries', keywords: 'fruit' },
      { char: '🍑', name: 'Peach', keywords: 'fruit' },
      { char: '🥭', name: 'Mango', keywords: 'fruit tropical' },
      { char: '🍍', name: 'Pineapple', keywords: 'fruit tropical' },
      { char: '🥥', name: 'Coconut', keywords: 'fruit tropical' },
      { char: '🥝', name: 'Kiwi fruit', keywords: 'fruit' },
      { char: '🍅', name: 'Tomato', keywords: 'vegetable' },
      { char: '🥕', name: 'Carrot', keywords: 'vegetable' },
      { char: '🌽', name: 'Ear of corn', keywords: 'vegetable maize' },
      { char: '🥔', name: 'Potato', keywords: 'vegetable' },
      { char: '🧅', name: 'Onion', keywords: 'vegetable' },
      { char: '🧄', name: 'Garlic', keywords: 'vegetable' },
      { char: '🥦', name: 'Broccoli', keywords: 'vegetable' },
      { char: '🫑', name: 'Bell pepper', keywords: 'vegetable capsicum' },
      { char: '🍞', name: 'Bread', keywords: 'loaf bakery' },
      { char: '🥐', name: 'Croissant', keywords: 'bakery pastry' },
      { char: '🧀', name: 'Cheese wedge', keywords: 'dairy' },
      { char: '🥚', name: 'Egg', keywords: 'dairy' },
      { char: '🥩', name: 'Cut of meat', keywords: 'steak beef' },
      { char: '🍗', name: 'Poultry leg', keywords: 'chicken meat' },
      { char: '🍔', name: 'Hamburger', keywords: 'burger fast food' },
      { char: '🍕', name: 'Pizza', keywords: 'fast food' },
      { char: '🌭', name: 'Hot dog', keywords: 'sausage fast food' },
      { char: '🌮', name: 'Taco', keywords: 'mexican' },
      { char: '🍜', name: 'Steaming bowl', keywords: 'noodles ramen soup' },
      { char: '🍣', name: 'Sushi', keywords: 'japanese fish' },
      { char: '🍚', name: 'Cooked rice', keywords: 'bowl' },
      { char: '🍦', name: 'Soft ice cream', keywords: 'dessert' },
      { char: '🍰', name: 'Shortcake', keywords: 'cake dessert' },
      { char: '🍪', name: 'Cookie', keywords: 'biscuit dessert' },
      { char: '🍫', name: 'Chocolate bar', keywords: 'sweet dessert' },
      { char: '🍬', name: 'Candy', keywords: 'sweet' },
      { char: '🍿', name: 'Popcorn', keywords: 'snack cinema' },
      { char: '🧂', name: 'Salt', keywords: 'seasoning condiment' },
      { char: '☕', name: 'Hot beverage', keywords: 'coffee tea drink' },
      { char: '🍵', name: 'Teacup without handle', keywords: 'tea drink' },
      { char: '🍺', name: 'Beer mug', keywords: 'drink alcohol' },
      { char: '🍷', name: 'Wine glass', keywords: 'drink alcohol' },
      { char: '🥤', name: 'Cup with straw', keywords: 'drink soda' },
      { char: '🍼', name: 'Baby bottle', keywords: 'milk' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & places',
    emojis: [
      { char: '🚗', name: 'Automobile', keywords: 'car vehicle' },
      { char: '🚕', name: 'Taxi', keywords: 'cab car' },
      { char: '🚙', name: 'Sport utility vehicle', keywords: 'suv car' },
      { char: '🚌', name: 'Bus', keywords: 'vehicle transport' },
      { char: '🚚', name: 'Delivery truck', keywords: 'lorry van shipping' },
      { char: '🚛', name: 'Articulated lorry', keywords: 'truck freight' },
      { char: '🚜', name: 'Tractor', keywords: 'farm vehicle' },
      { char: '🏍️', name: 'Motorcycle', keywords: 'motorbike vehicle' },
      { char: '🚲', name: 'Bicycle', keywords: 'bike cycle' },
      { char: '🛴', name: 'Kick scooter', keywords: 'scooter' },
      { char: '✈️', name: 'Airplane', keywords: 'plane flight travel' },
      { char: '🚀', name: 'Rocket', keywords: 'space launch' },
      { char: '🚁', name: 'Helicopter', keywords: 'aircraft' },
      { char: '⛵', name: 'Sailboat', keywords: 'boat sea' },
      { char: '🚢', name: 'Ship', keywords: 'boat cruise sea' },
      { char: '🚂', name: 'Locomotive', keywords: 'train railway' },
      { char: '🚆', name: 'Train', keywords: 'railway transport' },
      { char: '⚓', name: 'Anchor', keywords: 'ship nautical' },
      { char: '⛽', name: 'Fuel pump', keywords: 'petrol gas station' },
      { char: '🚦', name: 'Vertical traffic light', keywords: 'signal' },
      { char: '🗺️', name: 'World map', keywords: 'atlas travel location' },
      { char: '🧭', name: 'Compass', keywords: 'navigation direction' },
      { char: '🏔️', name: 'Snow-capped mountain', keywords: 'peak' },
      { char: '🏕️', name: 'Camping', keywords: 'tent outdoors' },
      { char: '🏖️', name: 'Beach with umbrella', keywords: 'holiday sea' },
      { char: '🏠', name: 'House', keywords: 'home building' },
      { char: '🏡', name: 'House with garden', keywords: 'home' },
      { char: '🏢', name: 'Office building', keywords: 'work company' },
      { char: '🏭', name: 'Factory', keywords: 'industry manufacturing' },
      { char: '🏥', name: 'Hospital', keywords: 'medical' },
      { char: '🏦', name: 'Bank', keywords: 'money' },
      { char: '🏪', name: 'Convenience store', keywords: 'shop' },
      { char: '🏬', name: 'Department store', keywords: 'shop mall' },
      { char: '🏗️', name: 'Building construction', keywords: 'crane site' },
      { char: '🗄️', name: 'File cabinet', keywords: 'storage archive drawers' },
      { char: '📦', name: 'Package', keywords: 'box parcel shipping storage' },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    emojis: [
      { char: '⚽', name: 'Soccer ball', keywords: 'football sport' },
      { char: '🏀', name: 'Basketball', keywords: 'sport' },
      { char: '🏈', name: 'American football', keywords: 'sport' },
      { char: '⚾', name: 'Baseball', keywords: 'sport' },
      { char: '🎾', name: 'Tennis', keywords: 'sport racket' },
      { char: '🏐', name: 'Volleyball', keywords: 'sport' },
      { char: '🏉', name: 'Rugby football', keywords: 'sport' },
      { char: '🎱', name: 'Pool 8 ball', keywords: 'billiards snooker' },
      { char: '🏓', name: 'Ping pong', keywords: 'table tennis sport' },
      { char: '🏸', name: 'Badminton', keywords: 'sport racket' },
      { char: '🥅', name: 'Goal net', keywords: 'sport' },
      { char: '⛳', name: 'Flag in hole', keywords: 'golf' },
      { char: '🎣', name: 'Fishing pole', keywords: 'fish rod' },
      { char: '🎿', name: 'Skis', keywords: 'ski snow sport' },
      { char: '🛹', name: 'Skateboard', keywords: 'skate' },
      { char: '🎯', name: 'Direct hit', keywords: 'dartboard target aim' },
      { char: '🎮', name: 'Video game', keywords: 'gaming controller' },
      { char: '🕹️', name: 'Joystick', keywords: 'game arcade' },
      { char: '🎲', name: 'Game die', keywords: 'dice board game' },
      { char: '🧩', name: 'Puzzle piece', keywords: 'jigsaw' },
      { char: '♟️', name: 'Chess pawn', keywords: 'game strategy' },
      { char: '🎨', name: 'Artist palette', keywords: 'paint art colour' },
      { char: '🎭', name: 'Performing arts', keywords: 'theatre masks drama' },
      { char: '🎬', name: 'Clapper board', keywords: 'film movie cinema' },
      { char: '🎤', name: 'Microphone', keywords: 'sing karaoke audio' },
      { char: '🎧', name: 'Headphone', keywords: 'audio music listen' },
      { char: '🎼', name: 'Musical score', keywords: 'music notes' },
      { char: '🎹', name: 'Musical keyboard', keywords: 'piano music' },
      { char: '🥁', name: 'Drum', keywords: 'music percussion' },
      { char: '🎸', name: 'Guitar', keywords: 'music instrument' },
      { char: '🎺', name: 'Trumpet', keywords: 'music brass' },
      { char: '🎻', name: 'Violin', keywords: 'music strings' },
      { char: '🎳', name: 'Bowling', keywords: 'sport' },
      { char: '🎪', name: 'Circus tent', keywords: 'carnival' },
      { char: '🃏', name: 'Joker', keywords: 'playing card trading deck' },
      { char: '🎴', name: 'Flower playing cards', keywords: 'trading card game hanafuda' },
      { char: '🎉', name: 'Party popper', keywords: 'celebrate party' },
      { char: '🎁', name: 'Wrapped gift', keywords: 'present box' },
      { char: '🏆', name: 'Trophy', keywords: 'award win prize' },
      { char: '🏅', name: 'Sports medal', keywords: 'award win' },
      { char: '🎖️', name: 'Military medal', keywords: 'award honour' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emojis: [
      { char: '🔋', name: 'Battery', keywords: 'power cell charge energy' },
      { char: '🪫', name: 'Low battery', keywords: 'power empty' },
      { char: '🔌', name: 'Electric plug', keywords: 'power socket cable' },
      { char: '💡', name: 'Light bulb', keywords: 'idea lamp electric' },
      { char: '🔦', name: 'Flashlight', keywords: 'torch light' },
      { char: '🕯️', name: 'Candle', keywords: 'light flame' },
      { char: '💻', name: 'Laptop', keywords: 'computer pc' },
      { char: '🖥️', name: 'Desktop computer', keywords: 'monitor pc' },
      { char: '⌨️', name: 'Keyboard', keywords: 'computer typing' },
      { char: '🖱️', name: 'Computer mouse', keywords: 'pointer' },
      { char: '🖨️', name: 'Printer', keywords: 'print' },
      { char: '💾', name: 'Floppy disk', keywords: 'save storage disk' },
      { char: '💿', name: 'Optical disk', keywords: 'cd dvd media' },
      { char: '📀', name: 'DVD', keywords: 'disc media' },
      { char: '📱', name: 'Mobile phone', keywords: 'smartphone cell' },
      { char: '☎️', name: 'Telephone', keywords: 'phone call' },
      { char: '📷', name: 'Camera', keywords: 'photo' },
      { char: '📹', name: 'Video camera', keywords: 'record film' },
      { char: '📺', name: 'Television', keywords: 'tv screen' },
      { char: '📻', name: 'Radio', keywords: 'audio' },
      { char: '⏰', name: 'Alarm clock', keywords: 'time' },
      { char: '⌚', name: 'Watch', keywords: 'time wrist' },
      { char: '🔭', name: 'Telescope', keywords: 'astronomy space' },
      { char: '🔬', name: 'Microscope', keywords: 'science lab' },
      { char: '🧪', name: 'Test tube', keywords: 'science chemistry lab' },
      { char: '🧬', name: 'DNA', keywords: 'biology science' },
      { char: '💊', name: 'Pill', keywords: 'medicine drug' },
      { char: '💉', name: 'Syringe', keywords: 'medicine injection vaccine' },
      { char: '🩹', name: 'Adhesive bandage', keywords: 'plaster first aid' },
      { char: '🔧', name: 'Wrench', keywords: 'spanner tool repair' },
      { char: '🔨', name: 'Hammer', keywords: 'tool diy' },
      { char: '🛠️', name: 'Hammer and wrench', keywords: 'tools repair' },
      { char: '🪛', name: 'Screwdriver', keywords: 'tool diy' },
      { char: '🔩', name: 'Nut and bolt', keywords: 'screw fastener hardware' },
      { char: '⚙️', name: 'Gear', keywords: 'cog settings mechanical' },
      { char: '🧰', name: 'Toolbox', keywords: 'tools kit' },
      { char: '🧲', name: 'Magnet', keywords: 'magnetic' },
      { char: '🪜', name: 'Ladder', keywords: 'steps climb' },
      { char: '🪚', name: 'Carpentry saw', keywords: 'tool wood cut' },
      { char: '🧱', name: 'Brick', keywords: 'wall building' },
      { char: '⛓️', name: 'Chains', keywords: 'link metal' },
      { char: '🔗', name: 'Link', keywords: 'chain url connect' },
      { char: '📎', name: 'Paperclip', keywords: 'attach office' },
      { char: '📏', name: 'Straight ruler', keywords: 'measure length' },
      { char: '📐', name: 'Triangular ruler', keywords: 'measure angle set square' },
      { char: '✂️', name: 'Scissors', keywords: 'cut craft' },
      { char: '🖊️', name: 'Pen', keywords: 'write' },
      { char: '✏️', name: 'Pencil', keywords: 'write draw' },
      { char: '🖌️', name: 'Paintbrush', keywords: 'paint art' },
      { char: '🖍️', name: 'Crayon', keywords: 'colour draw' },
      { char: '🧵', name: 'Thread', keywords: 'sewing spool' },
      { char: '🧶', name: 'Yarn', keywords: 'knitting wool craft' },
      { char: '🪡', name: 'Sewing needle', keywords: 'stitch craft' },
      { char: '👕', name: 'T-shirt', keywords: 'clothing shirt' },
      { char: '👗', name: 'Dress', keywords: 'clothing' },
      { char: '👖', name: 'Jeans', keywords: 'clothing trousers' },
      { char: '🧥', name: 'Coat', keywords: 'clothing jacket' },
      { char: '👟', name: 'Running shoe', keywords: 'trainer footwear' },
      { char: '👞', name: 'Man’s shoe', keywords: 'footwear' },
      { char: '👜', name: 'Handbag', keywords: 'bag' },
      { char: '🎒', name: 'Backpack', keywords: 'bag rucksack' },
      { char: '👓', name: 'Glasses', keywords: 'spectacles eyewear' },
      { char: '⌛', name: 'Hourglass', keywords: 'time sand' },
      { char: '📖', name: 'Open book', keywords: 'read manual' },
      { char: '📚', name: 'Books', keywords: 'library read' },
      { char: '📕', name: 'Closed book', keywords: 'read novel' },
      { char: '📓', name: 'Notebook', keywords: 'journal write' },
      { char: '📒', name: 'Ledger', keywords: 'accounts record' },
      { char: '📰', name: 'Newspaper', keywords: 'news press' },
      { char: '🗞️', name: 'Rolled-up newspaper', keywords: 'news' },
      { char: '💰', name: 'Money bag', keywords: 'cash savings' },
      { char: '💵', name: 'Dollar banknote', keywords: 'money cash' },
      { char: '💳', name: 'Credit card', keywords: 'payment money' },
      { char: '🪙', name: 'Coin', keywords: 'money currency' },
      { char: '🔑', name: 'Key', keywords: 'lock unlock access' },
      { char: '🔒', name: 'Locked', keywords: 'lock secure private' },
      { char: '🔓', name: 'Unlocked', keywords: 'lock open' },
      { char: '🛡️', name: 'Shield', keywords: 'protect security defence' },
      { char: '🧯', name: 'Fire extinguisher', keywords: 'safety fire' },
      { char: '🧴', name: 'Lotion bottle', keywords: 'soap liquid' },
      { char: '🧷', name: 'Safety pin', keywords: 'pin' },
      { char: '🧹', name: 'Broom', keywords: 'sweep clean' },
      { char: '🧽', name: 'Sponge', keywords: 'clean wash' },
      { char: '🧺', name: 'Basket', keywords: 'laundry storage' },
      { char: '🪣', name: 'Bucket', keywords: 'pail water' },
      { char: '🛒', name: 'Shopping cart', keywords: 'trolley buy' },
      { char: '⚗️', name: 'Alembic', keywords: 'chemistry distil lab' },
      { char: '🌡️', name: 'Thermometer', keywords: 'temperature' },
      { char: '🧑‍💻', name: 'Technologist', keywords: 'developer coder' },
      { char: '🔫', name: 'Water pistol', keywords: 'toy gun' },
      { char: '🎈', name: 'Balloon', keywords: 'party' },
      { char: '🪃', name: 'Boomerang', keywords: 'throw' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emojis: [
      { char: '✅', name: 'Check mark button', keywords: 'tick done yes ok' },
      { char: '✔️', name: 'Check mark', keywords: 'tick done' },
      { char: '❌', name: 'Cross mark', keywords: 'no wrong delete' },
      { char: '➕', name: 'Plus', keywords: 'add' },
      { char: '➖', name: 'Minus', keywords: 'subtract remove' },
      { char: '➗', name: 'Divide', keywords: 'division' },
      { char: '✖️', name: 'Multiply', keywords: 'times multiplication' },
      { char: '❓', name: 'Question mark', keywords: 'help unknown' },
      { char: '❗', name: 'Exclamation mark', keywords: 'warning important' },
      { char: '⚠️', name: 'Warning', keywords: 'caution alert' },
      { char: '🚫', name: 'Prohibited', keywords: 'no forbidden ban' },
      { char: '♻️', name: 'Recycling symbol', keywords: 'recycle reuse eco' },
      { char: '⭕', name: 'Hollow red circle', keywords: 'circle o' },
      { char: '🔴', name: 'Red circle', keywords: 'dot status' },
      { char: '🟠', name: 'Orange circle', keywords: 'dot status' },
      { char: '🟡', name: 'Yellow circle', keywords: 'dot status' },
      { char: '🟢', name: 'Green circle', keywords: 'dot status ok' },
      { char: '🔵', name: 'Blue circle', keywords: 'dot status' },
      { char: '🟣', name: 'Purple circle', keywords: 'dot status' },
      { char: '⚫', name: 'Black circle', keywords: 'dot' },
      { char: '⚪', name: 'White circle', keywords: 'dot' },
      { char: '🟥', name: 'Red square', keywords: 'block colour' },
      { char: '🟧', name: 'Orange square', keywords: 'block colour' },
      { char: '🟨', name: 'Yellow square', keywords: 'block colour' },
      { char: '🟩', name: 'Green square', keywords: 'block colour' },
      { char: '🟦', name: 'Blue square', keywords: 'block colour' },
      { char: '⬛', name: 'Black square', keywords: 'block' },
      { char: '⬜', name: 'White square', keywords: 'block' },
      { char: '🔶', name: 'Large orange diamond', keywords: 'shape' },
      { char: '🔷', name: 'Large blue diamond', keywords: 'shape' },
      { char: '💠', name: 'Diamond with a dot', keywords: 'gem shape' },
      { char: '🔺', name: 'Red triangle pointed up', keywords: 'shape increase' },
      { char: '🔻', name: 'Red triangle pointed down', keywords: 'shape decrease' },
      { char: '⬆️', name: 'Up arrow', keywords: 'direction' },
      { char: '⬇️', name: 'Down arrow', keywords: 'direction' },
      { char: '⬅️', name: 'Left arrow', keywords: 'direction back' },
      { char: '➡️', name: 'Right arrow', keywords: 'direction next' },
      { char: '🔄', name: 'Counterclockwise arrows', keywords: 'refresh sync cycle' },
      { char: '🔁', name: 'Repeat', keywords: 'loop' },
      { char: '⏳', name: 'Hourglass not done', keywords: 'wait time pending' },
      { char: '⚛️', name: 'Atom symbol', keywords: 'science physics' },
      { char: '☢️', name: 'Radioactive', keywords: 'nuclear hazard' },
      { char: '☣️', name: 'Biohazard', keywords: 'hazard danger' },
      { char: '⚕️', name: 'Medical symbol', keywords: 'health caduceus' },
      { char: '♾️', name: 'Infinity', keywords: 'unlimited endless' },
      { char: '🔔', name: 'Bell', keywords: 'alert notification' },
      { char: '📌', name: 'Pushpin', keywords: 'pin mark location' },
      { char: '📍', name: 'Round pushpin', keywords: 'pin location map' },
      { char: '🏷️', name: 'Label', keywords: 'tag price' },
      { char: '🔖', name: 'Bookmark', keywords: 'tag mark' },
      { char: '#️⃣', name: 'Hash', keywords: 'number pound' },
      { char: '💤', name: 'Zzz', keywords: 'sleep' },
      { char: '💢', name: 'Anger symbol', keywords: 'mad' },
      { char: '💬', name: 'Speech balloon', keywords: 'chat message comment' },
      { char: '🔍', name: 'Magnifying glass', keywords: 'search find zoom' },
    ],
  },
];

/**
 * Every emoji, flattened in group order — the search corpus and the "All" group's contents.
 * Computed once at module load.
 */
export const ALL_EMOJIS: readonly EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.emojis);
