/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as ShareTargetRouteImport } from './routes/share-target'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InsuranceScheduleRouteImport } from './routes/insurance-schedule'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HomeAssistantRouteImport } from './routes/home-assistant'
import { Route as DeepLinkRouteImport } from './routes/deep-link'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTargetRoute = ShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceScheduleRoute = InsuranceScheduleRouteImport.update({
  id: '/insurance-schedule',
  path: '/insurance-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAssistantRoute = HomeAssistantRouteImport.update({
  id: '/home-assistant',
  path: '/home-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepLinkRoute = DeepLinkRouteImport.update({
  id: '/deep-link',
  path: '/deep-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/bookings': typeof BookingsRoute
  '/catalogue': typeof CatalogueRoute
  '/contacts': typeof ContactsRoute
  '/deep-link': typeof DeepLinkRoute
  '/home-assistant': typeof HomeAssistantRoute
  '/import': typeof ImportRoute
  '/insurance-schedule': typeof InsuranceScheduleRoute
  '/inventory': typeof InventoryRoute
  '/modules': typeof ModulesRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/share-target': typeof ShareTargetRoute
  '/sync': typeof SyncRoute
  '/tags': typeof TagsRoute
  '/upcoming': typeof UpcomingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/bookings': typeof BookingsRoute
  '/catalogue': typeof CatalogueRoute
  '/contacts': typeof ContactsRoute
  '/deep-link': typeof DeepLinkRoute
  '/home-assistant': typeof HomeAssistantRoute
  '/import': typeof ImportRoute
  '/insurance-schedule': typeof InsuranceScheduleRoute
  '/inventory': typeof InventoryRoute
  '/modules': typeof ModulesRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/share-target': typeof ShareTargetRoute
  '/sync': typeof SyncRoute
  '/tags': typeof TagsRoute
  '/upcoming': typeof UpcomingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/bookings': typeof BookingsRoute
  '/catalogue': typeof CatalogueRoute
  '/contacts': typeof ContactsRoute
  '/deep-link': typeof DeepLinkRoute
  '/home-assistant': typeof HomeAssistantRoute
  '/import': typeof ImportRoute
  '/insurance-schedule': typeof InsuranceScheduleRoute
  '/inventory': typeof InventoryRoute
  '/modules': typeof ModulesRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/share-target': typeof ShareTargetRoute
  '/sync': typeof SyncRoute
  '/tags': typeof TagsRoute
  '/upcoming': typeof UpcomingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/alerts'
    | '/bookings'
    | '/catalogue'
    | '/contacts'
    | '/deep-link'
    | '/home-assistant'
    | '/import'
    | '/insurance-schedule'
    | '/inventory'
    | '/modules'
    | '/projects'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/share-target'
    | '/sync'
    | '/tags'
    | '/upcoming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/alerts'
    | '/bookings'
    | '/catalogue'
    | '/contacts'
    | '/deep-link'
    | '/home-assistant'
    | '/import'
    | '/insurance-schedule'
    | '/inventory'
    | '/modules'
    | '/projects'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/share-target'
    | '/sync'
    | '/tags'
    | '/upcoming'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/alerts'
    | '/bookings'
    | '/catalogue'
    | '/contacts'
    | '/deep-link'
    | '/home-assistant'
    | '/import'
    | '/insurance-schedule'
    | '/inventory'
    | '/modules'
    | '/projects'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/share-target'
    | '/sync'
    | '/tags'
    | '/upcoming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  BookingsRoute: typeof BookingsRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactsRoute: typeof ContactsRoute
  DeepLinkRoute: typeof DeepLinkRoute
  HomeAssistantRoute: typeof HomeAssistantRoute
  ImportRoute: typeof ImportRoute
  InsuranceScheduleRoute: typeof InsuranceScheduleRoute
  InventoryRoute: typeof InventoryRoute
  ModulesRoute: typeof ModulesRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShareTargetRoute: typeof ShareTargetRoute
  SyncRoute: typeof SyncRoute
  TagsRoute: typeof TagsRoute
  UpcomingRoute: typeof UpcomingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-target': {
      id: '/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof ShareTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-schedule': {
      id: '/insurance-schedule'
      path: '/insurance-schedule'
      fullPath: '/insurance-schedule'
      preLoaderRoute: typeof InsuranceScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-assistant': {
      id: '/home-assistant'
      path: '/home-assistant'
      fullPath: '/home-assistant'
      preLoaderRoute: typeof HomeAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-link': {
      id: '/deep-link'
      path: '/deep-link'
      fullPath: '/deep-link'
      preLoaderRoute: typeof DeepLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  BookingsRoute: BookingsRoute,
  CatalogueRoute: CatalogueRoute,
  ContactsRoute: ContactsRoute,
  DeepLinkRoute: DeepLinkRoute,
  HomeAssistantRoute: HomeAssistantRoute,
  ImportRoute: ImportRoute,
  InsuranceScheduleRoute: InsuranceScheduleRoute,
  InventoryRoute: InventoryRoute,
  ModulesRoute: ModulesRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShareTargetRoute: ShareTargetRoute,
  SyncRoute: SyncRoute,
  TagsRoute: TagsRoute,
  UpcomingRoute: UpcomingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
